### ISSUE TITLE
compass create only makes /css and /sass directories

### ISSUE THREAD

**Issue by dandineen** [codingdesigner/Survival-Kit#4]
Hello,

I'm completely new to using the command line, Ruby and Github so I have a feeling I'm missing something obvious here. Apologies if this is a really basic question.

I've installed the survivalkit gem successfully and have been trying to create a survival kit based template site via 'compass create'. The command seems to run fine but when I list the files in the target directory I only have the basic Compass /css and /sass directories present. There are no actual files in the directories.

Using 'Compass install survivalkit' on an existing project creates an additional JS directory with a number of sub-directories but, again, no actual files. It also creates the empty sub-directories for the SASS partials and survivalkit.

Do I need to download all of the files from Github and place them in a specific location for the gem to be able to install them? If so, where should I store these files by default.

If the HTML/CSS install should be happening automatically do you think it is my configuration of Ruby/Compass/Sass that is at fault?

I look forward to any help you may be able to provide.

Regards

Dan

**Comment by dandineen** [comment]
Hi,

I've just retried the 'compass create' command, although this time I actually remembered to type in the -u survivalkit as well as the -r. Everything installed perfectly.

I'll close the door on my way out ;-)

**Comment by codingdesigner** [comment]
Hey Dan, 

I'm glad you found your solution. If you're new to the command line, ruby, and git then your first step is a big one. Let me know if you need any help. I'm always keen to learn where the hard parts are for new users. 

FYI, I'm actually not much of a Ruby guy myself. I work mostly in PHP and all my Sass projects are standalone, rather than rails projects. 

Hope you have fun with the kit!
